In [1]:
import torch

# Tensor

In [46]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [47]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [48]:
print(y.grad_fn)

In [49]:
z = y * y * 3
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>)


In [50]:
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [51]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [52]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [53]:
b = (a * a).sum()
print(b.grad_fn)

# Gradients

In [54]:
out = z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward1>)


In [55]:
out.backward()
print(out)

tensor(27., grad_fn=<MeanBackward1>)


**Because out contains a single scalar, out.backward() is equivalent to out.backward(torch.tensor(1)).**

In [56]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


$
o = \frac{1}{4} \sum_{i}z_{i}
\\ z_{i} = 3(x_{i}+2)^2 \rightarrow \left.z_i \right|_{x_i = 1} = 27
\\ \frac{\partial o}{\partial x} = \frac{3}{2}(x_i + 2) \rightarrow \left.{\frac{\partial o}{\partial x}} \right|_{x_i = 1} = \frac{9}{2} = 4.5
$

In [65]:
x = torch.randn(3, requires_grad=True)
print(x)
print(x.grad)

tensor([-1.0617,  1.1143,  0.9000], requires_grad=True)
None


In [71]:
y = x * 2
print(y)
while y.data.norm() < 1000:
    y = y * 2
    print(y)

tensor([-2.1235,  2.2286,  1.8000], grad_fn=<MulBackward>)
tensor([-4.2470,  4.4571,  3.5999], grad_fn=<MulBackward>)
tensor([-8.4940,  8.9143,  7.1998], grad_fn=<MulBackward>)
tensor([-16.9880,  17.8285,  14.3997], grad_fn=<MulBackward>)
tensor([-33.9760,  35.6570,  28.7994], grad_fn=<MulBackward>)
tensor([-67.9519,  71.3141,  57.5988], grad_fn=<MulBackward>)
tensor([-135.9038,  142.6281,  115.1976], grad_fn=<MulBackward>)
tensor([-271.8076,  285.2562,  230.3951], grad_fn=<MulBackward>)
tensor([-543.6153,  570.5125,  460.7903], grad_fn=<MulBackward>)
tensor([-1087.2306,  1141.0249,   921.5806], grad_fn=<MulBackward>)


In [72]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
print(gradients)
y.backward(gradients)
print(y)

tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])
tensor([-1087.2306,  1141.0249,   921.5806], grad_fn=<MulBackward>)


In [73]:
print(x)
print(x.grad)

tensor([-1.0617,  1.1143,  0.9000], requires_grad=True)
tensor([ 204.8000, 2048.0000,    0.2048])


In [74]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
