In [19]:
import numpy as np
import torch

# Getting Started

### Tensors

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 4.6566e-10, 0.0000e+00],
        [4.6566e-10, 3.7253e-08, 4.7545e+30],
        [1.3569e-14, 9.3323e-40, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.6566e-10, 8.2856e-21]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2203, 0.8742, 0.8378],
        [0.0189, 0.5637, 0.1702],
        [0.5467, 0.0967, 0.0034],
        [0.5256, 0.9581, 0.8015],
        [0.9878, 0.6925, 0.8340]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[ 1.2958, -1.2988,  0.1397],
        [-1.3708,  0.5500,  1.1750],
        [-3.0485,  0.6949, -0.1798],
        [ 0.1894,  0.5757,  0.4673],
        [ 0.5411, -1.2625, -0.5206]])


In [8]:
print(x.size())

torch.Size([5, 3])


**torch.Size() is in fact a tuple, so it supports all tuple operations.**

### Operations

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.1682, -0.7500,  0.9278],
        [-0.6893,  1.4893,  1.7314],
        [-2.9913,  1.3700,  0.0582],
        [ 0.8613,  1.1643,  0.4844],
        [ 0.5688, -1.1457,  0.2108]])


In [10]:
print(torch.add(x, y))

tensor([[ 2.1682, -0.7500,  0.9278],
        [-0.6893,  1.4893,  1.7314],
        [-2.9913,  1.3700,  0.0582],
        [ 0.8613,  1.1643,  0.4844],
        [ 0.5688, -1.1457,  0.2108]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.1682, -0.7500,  0.9278],
        [-0.6893,  1.4893,  1.7314],
        [-2.9913,  1.3700,  0.0582],
        [ 0.8613,  1.1643,  0.4844],
        [ 0.5688, -1.1457,  0.2108]])


In [12]:
y.add_(x) # adds x to y
print(y)

tensor([[ 2.1682, -0.7500,  0.9278],
        [-0.6893,  1.4893,  1.7314],
        [-2.9913,  1.3700,  0.0582],
        [ 0.8613,  1.1643,  0.4844],
        [ 0.5688, -1.1457,  0.2108]])


**Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.**

In [13]:
print(x[:, 1])

tensor([-1.2988,  0.5500,  0.6949,  0.5757, -1.2625])


In [14]:
x = torch.randn(4, 4)
y = x.view(16) #  resize/reshape tensor
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5014])
0.5013514161109924


# NumPy Bridge

### Converting a Torch Tensor to a NumPy Array

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

In [20]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors

In [23]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print('There is no CUDA here.')

There is no CUDA here.
